package movement;

import core.Coord;
import core.Settings;
import core.SettingsError;

import java.util.ArrayList;
import java.util.List;

/**
 * Movement model which moves on a path generated by
 * the GDRRT* algorithm to go from start location to end location
 */
public class GDRRTMovement extends MovementModel implements SwitchableMovement {
    public static final String GDRRT_MOVEMENT_NS = "GDRRTMovement.";

    // per node setting for defining the start & end location
    public static final String START_LOCATION_S = "startLocation";
    public static final String END_LOCATION_S = "endLocation";

    // setting that specifies the files containing the obstacles to avoid
    public static final String OBSTACLE_FILE_S = "obstacleFile";

    // For prototype to handle multiple hosts
    private List<Coord> startLocs;
    private List<Coord> endLocs;
    private static int nextHostIndex = 0;

    // starting location of the node
    private Coord startLoc;
    // ending location of the node
    private Coord endLoc;
    private String obstacleFilePath;
    private boolean reachedEnd = false;
    private GDRRTPlanner gdrrt;
    private boolean isWaiting = false;
    private boolean isDead = false;
    private double currentPriority = -1.0;
    private long totalComputeTimeNs = 0;
    private double totalTurnCost = 0.0;
    private Double lastHeading = null;

    /**
     * Creates a new movement model based on a Settings object's settings.
     *
     * @param s The Settings object where the settings are read from
     */
    public GDRRTMovement(Settings s) {
        super(s);
        // Read arrays of coordinates for multiple drones
        this.startLocs = parseCoords(s, GDRRT_MOVEMENT_NS + START_LOCATION_S);
        this.endLocs = parseCoords(s, GDRRT_MOVEMENT_NS + END_LOCATION_S);

        if (startLocs.size() != endLocs.size()) {
            throw new SettingsError("Start and end location arrays must have the same size");
        }

        int nrofHosts = s.getInt(core.SimScenario.NROF_HOSTS_S);
        if (startLocs.size() < nrofHosts) {
            throw new SettingsError("Not enough start/end locations for all hosts in the group");
        }

        this.obstacleFilePath = s.getSetting(GDRRT_MOVEMENT_NS + OBSTACLE_FILE_S);
        this.gdrrt = new GDRRTPlanner(this.obstacleFilePath);
        nextHostIndex = 0;
    }

    // Helper to parse coordinate arrays like "[x1,y1; x2,y2]"
    private List<Coord> parseCoords(Settings s, String key) {
        // get the full raw string of coordinates
        String raw = s.getRawSetting(key);
        raw = raw.replace("[", "").replace("]", "");
        String[] pairs = raw.split(";");
        List<Coord> coords = new ArrayList<>();
        for (String pair : pairs) {
            String[] values = pair.split(",");
            if (values.length != 2) {
                throw new SettingsError("Invalid coordinate pair: " + pair + " in setting " + key);
            }
            coords.add(new Coord(Double.parseDouble(values[0].trim()), Double.parseDouble(values[1].trim())));
        }
        return coords;
    }

    /**
     * Copy constructor used for each node in group
     * @param proto
     */
    public GDRRTMovement(GDRRTMovement proto) {
        super(proto);
        // Assign a unique start/end location to this instance
        this.startLoc = proto.startLocs.get(nextHostIndex);
        this.endLoc = proto.endLocs.get(nextHostIndex);
        nextHostIndex++;
        this.isDead = proto.isDead;
        this.currentPriority = proto.currentPriority;

        this.obstacleFilePath = proto.obstacleFilePath;
        this.gdrrt = new GDRRTPlanner(this.obstacleFilePath);
    }

    @Override
    public GDRRTMovement replicate() {
        return new GDRRTMovement(this);
    }

    public double getPriority() {
        if (currentPriority < 0 && getHost() != null) {
            currentPriority = 1.0 + getHost().getAddress();
        }
        return currentPriority;
    }

    public void setPriority(double priority) {
        this.currentPriority = priority;
    }

    @Override
    public Path getPath() {
        long startNs = System.nanoTime();
        try {
            if (reachedEnd || isDead) {
                return null;
            }

            // Check if the drone has physically reached the destination
            if (getHost() != null && getHost().getLocation().distance(endLoc) < 1.0) {
                reachedEnd = true;
                DronePathManager.setStationary(getHost().getAddress(), getHost().getLocation());
                System.out.println("Drone " + getHost().getAddress() + " successfully reached its goal at " + core.SimClock.getTime() + "s!");

                return null;
            }

            // getPath called for the first time
            if (gdrrt == null) {
                gdrrt = new GDRRTPlanner(this.obstacleFilePath);
            }

            if (!gdrrt.isInitialized()) {
                gdrrt.init(getHost().getLocation(), endLoc);
            }

            // Plan the next move without committing
            GDRRTPlanner.PlannedSegment proposedSegment = gdrrt.planNextSegment();

            // Check if a path was found
            if (proposedSegment == null) {
                reachedEnd = true;
                System.out.println("Drone " + getHost().getAddress()
                        + " planner returned null. Setting reachedEnd = true and giving up.");
                DronePathManager.setStationary(getHost().getAddress(), getHost().getLocation());
                return null;
            }

            // Request permission from the path manager
            if (DronePathManager.requestPath(getHost().getAddress(), proposedSegment.path)) {
                // Permission granted, commit and move
                isWaiting = false;
                gdrrt.commit(proposedSegment);

                updateTurnCost(proposedSegment.path);
                return proposedSegment.path;
            } else {
                // Permission denied, wait
                isWaiting = true;
                DronePathManager.setStationary(getHost().getAddress(), getHost().getLocation());

                gdrrt.init(getHost().getLocation(), endLoc);

                // Return a path that keeps the drone stationary
                Path waitingPath = new Path(0);
                waitingPath.addWaypoint(getHost().getLocation());
                return waitingPath;
            }
        } finally {
            this.totalComputeTimeNs += (System.nanoTime() - startNs);
        }
    }

    public boolean isDone() {
        return reachedEnd;
    }

    @Override
    public boolean isReady() {
        return reachedEnd;
    }
    
    public boolean isDead() {
        return isDead;
    }

    // Removing & stopping path calculation for the node
    public void kill() {
        this.isDead = true;
        this.reachedEnd = true;
        
        // Release path ownership to unblock airspace
        if (getHost() != null) {
            if (getHost().getPath() != null) {
                getHost().getPath().getCoords().clear();
            }
            DronePathManager.setStationary(getHost().getAddress(), getHost().getLocation());
            System.out.println("Drone " + getHost().getAddress() + " was SHOT DOWN at " + core.SimClock.getTime() + "s!");
        }
    }

    // Update the target for the node
    public void changeTarget(Coord newTarget, double newPriority) {
        this.endLoc = newTarget;
        this.reachedEnd = false;
        this.currentPriority = newPriority;
        // Reinitialize the GDRRT planner with current location and the new higher priority target
        this.gdrrt.init(getHost().getLocation(), newTarget);
        
        // Abort the drone's ongoing movement to force a new path request
        if (getHost() != null) {
            if (getHost().getPath() != null) {
                getHost().getPath().getCoords().clear();
            }
        }
        System.out.println("Drone " + getHost().getAddress() + " re-routed. New target: " + newTarget);
    }

    public boolean isDead() {
        return isDead;
    }

    public void kill() {
        this.isDead = true;
        this.reachedEnd = true;

        // Release path ownership to unblock airspace
        if (getHost() != null) {
            if (getHost().getPath() != null) {
                getHost().getPath().getCoords().clear();
            }
        }
        DronePathManager.setStationary(getHost().getAddress());
        System.out.println("Drone " + getHost().getAddress() + " was SHOT DOWN at " + core.SimClock.getTime() + "s!");
    }

    public void changeTarget(Coord newTarget, double newPriority) {
        this.endLoc = newTarget;
        this.reachedEnd = false;
        this.currentPriority = newPriority;
        // Reinitialize the GDRRT planner with current location and the new higher priority target
        this.gdrrt.init(getHost().getLocation(), newTarget);

        // Immediately abort the drone's ongoing physical movement to force a new path request
        if (getHost() != null) {
            if (getHost().getPath() != null) {
                getHost().getPath().getCoords().clear();
            }
        }
        System.out.println("Drone " + getHost().getAddress() + " re-routed. New target: " + newTarget);
    }

    @Override
    public Coord getInitialLocation() {
        long startNs = System.nanoTime();
        try {
            this.totalTurnCost = 0.0;
            this.lastHeading = null;
            return this.startLoc.clone();
        } finally {
            this.totalComputeTimeNs += (System.nanoTime() - startNs);
        }
    }

    /**
     * Calculate the cost for turning in degrees
     * Used for generating reports
     */
    private void updateTurnCost(Path p) {
        if (p == null || p.getCoords().size() < 2) return;
        List<Coord> coords = p.getCoords();
        for (int i = 0; i < coords.size() - 1; i++) {
            Coord c1 = coords.get(i);
            Coord c2 = coords.get(i + 1);
            double dx = c2.getX() - c1.getX();
            double dy = c2.getY() - c1.getY();
            if (Math.hypot(dx, dy) > 1e-3) {
                double heading = Math.atan2(dy, dx);
                if (lastHeading != null) {
                    double diff = Math.abs(heading - lastHeading);
                    while (diff > Math.PI) diff -= 2 * Math.PI;
                    totalTurnCost += Math.abs(diff);
                }
                lastHeading = heading;
            }
        }
    }

    @Override
    public double nextPathAvailable() {
        if (reachedEnd || isDead) {
            return Double.MAX_VALUE;
        }
        if (isWaiting) {
            // try again after a short delay
            return core.SimClock.getTime() + 1.0;
        }
        return 0;
    }

    @Override
    public void setLocation(Coord lastWaypoint) {
        this.startLoc = lastWaypoint.clone();
    }

    @Override
    public Coord getLastLocation() {
        return getHost() != null ? getHost().getLocation().clone() : this.startLoc.clone();
    }

    public void setEndLocation(Coord endLoc) {
        this.endLoc = endLoc;
    }

    public Coord getEndLocation() {
        return this.endLoc;
    }

    public double getComputeTimeSeconds() {
        return this.totalComputeTimeNs / 1e9;
    }

    public double getPathSmoothness() {
        return this.totalTurnCost;
    }
}