package movement;

import core.Coord;
import core.Settings;
import core.SettingsError;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.*;
import java.util.*;

/**
 * Movement model which moves on a path generated by
 * the GDRRT* algorithm
 */
public class GDRRTMovement extends MovementModel {
    public static final String GDRRT_MOVEMENT_NS = "GDRRTMovement.";

    public static final String START_LOCATION_S = "startLocation";
    // per node group setting for defining the cordinate of the target
    public static final String END_LOCATION_S = "endLocation";
    public static final String OBSTACLE_FILE_S = "obstacleFile";

    // For prototype to handle multiple hosts
    private List<Coord> startLocs;
    private List<Coord> endLocs;
    private static int nextHostIndex = 0;

    // starting location of the node
    private Coord startLoc;
    // ending location of the node
    private Coord endLoc;
    private String obstacleFilePath;
    private boolean reachedEnd = false;
    private GDRRTPlanner gdrrt;
    private boolean isWaiting = false;

    /**
     * Creates a new movement model based on a Settings object's settings.
     * 
     * @param s The Settings object where the settings are read from
     */
    public GDRRTMovement(Settings s) {
        super(s);
        // Read arrays of coordinates for multiple drones
        this.startLocs = parseCoords(s, GDRRT_MOVEMENT_NS + START_LOCATION_S);
        this.endLocs = parseCoords(s, GDRRT_MOVEMENT_NS + END_LOCATION_S);

        if (startLocs.size() != endLocs.size()) {
            throw new SettingsError("Start and end location arrays must have the same size");
        }
        
        int nrofHosts = s.getInt(core.SimScenario.NROF_HOSTS_S);
        if (startLocs.size() < nrofHosts) {
            throw new SettingsError("Not enough start/end locations for all hosts in the group");
        }

        this.obstacleFilePath = s.getSetting(GDRRT_MOVEMENT_NS + OBSTACLE_FILE_S);
        this.gdrrt = new GDRRTPlanner(this.obstacleFilePath);
        nextHostIndex = 0; // Reset for each new group prototype
    }

    // Helper to parse coordinate arrays like "[x1,y1; x2,y2]"
    private List<Coord> parseCoords(Settings s, String key) {
        String raw = s.getSetting(key);
        raw = raw.replace("[", "").replace("]", "");
        String[] pairs = raw.split(";");
        List<Coord> coords = new ArrayList<>();
        for (String pair : pairs) {
            String[] values = pair.split(",");
            if (values.length != 2) {
                throw new SettingsError("Invalid coordinate pair: " + pair + " in setting " + key);
            }
            coords.add(new Coord(Double.parseDouble(values[0].trim()), Double.parseDouble(values[1].trim())));
        }
        return coords;
    }

    public GDRRTMovement(GDRRTMovement proto) {
        super(proto);
        // Assign a unique start/end location to this instance
        this.startLoc = proto.startLocs.get(nextHostIndex);
        this.endLoc = proto.endLocs.get(nextHostIndex);
        nextHostIndex++;

        this.obstacleFilePath = proto.obstacleFilePath;
        this.gdrrt = new GDRRTPlanner(this.obstacleFilePath);
    }

    public GDRRTMovement replicate() {
        return new GDRRTMovement(this);
    }
    
    @Override
    public Path getPath() {
        if (reachedEnd) {
            return null;
        }

        if (gdrrt == null) {
            gdrrt = new GDRRTPlanner(this.obstacleFilePath);
        }

        if (!gdrrt.isInitialized()) {
            gdrrt.init(getHost().getLocation(), endLoc);
        }

        // 1. Plan the next move without committing
        GDRRTPlanner.PlannedSegment proposedSegment = gdrrt.planNextSegment();

        if (proposedSegment == null) { // Planner couldn't find a path
            reachedEnd = true;
            DronePathManager.setStationary(getHost().getAddress());
            return null;
        }

        // 2. Request permission from the path manager
        if (DronePathManager.requestPath(getHost().getAddress(), proposedSegment.path)) {
            // 3a. Permission granted: commit and move
            isWaiting = false;
            gdrrt.commit(proposedSegment);
            
            if (proposedSegment.isFinalPath) {
                reachedEnd = true;
            }
            
            return proposedSegment.path;
        } else {
            // 3b. Permission denied: wait
            isWaiting = true;
            DronePathManager.setStationary(getHost().getAddress());
            
            // Return a path that keeps the drone stationary
            Path waitingPath = new Path(0);
            waitingPath.addWaypoint(getHost().getLocation());
            return waitingPath;
        }
    }

    @Override
    public Coord getInitialLocation() {
        Coord initLoc = this.startLoc.clone();
        return initLoc;
    }

    @Override
    public double nextPathAvailable() {
        if (reachedEnd) {
            return Double.MAX_VALUE;
        }
        if (isWaiting) {
            // If waiting, try again after a short delay to see if the path is clear.
            return core.SimClock.getTime() + 1.0;
        }
        return 0;
    }
}
