package movement;

import core.Coord;
import core.Settings;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.*;
import java.util.*;

/**
 * Movement model which moves on a path generated by
 * the GDRRT* algorithm
 */
public class GDRRTMovement extends MovementModel {
    public static final String GDRRT_MOVEMENT_NS = "GDRRTMovement.";

    public static final String START_LOCATION_S = "startLocation";
    // per node group setting for defining the cordinate of the target
    public static final String END_LOCATION_S = "endLocation";
    public static final String OBSTACLE_FILE_S = "obstacleFile";
    // store the generated path in file
    // private static String DRONE_ROUTE = "droneRoute";
    // starting location of the node
    private Coord startLoc;
    // ending location of the node
    private Coord endLoc;
    private String obstacleFilePath;
    private boolean reachedEnd = false;
    // private String drone_route;
    private GDRRTPlanner gdrrt;
    private Path nextPath;

    /**
     * Creates a new movement model based on a Settings object's settings.
     * 
     * @param s The Settings object where the settings are read from
     */
    public GDRRTMovement(Settings s) {
        super(s);
        double coords[];

        coords = s.getCsvDoubles(GDRRT_MOVEMENT_NS + START_LOCATION_S, 2);
        this.startLoc = new Coord(coords[0], coords[1]);
        coords = s.getCsvDoubles(GDRRT_MOVEMENT_NS + END_LOCATION_S, 2);
        this.endLoc = new Coord(coords[0], coords[1]);
        this.obstacleFilePath = s.getSetting(GDRRT_MOVEMENT_NS + OBSTACLE_FILE_S);
        // this.drone_route = s.getSetting(GDRRT_MOVEMENT_NS + DRONE_ROUTE);
        // We need MapRouteMovement for storing the obstacles WKT file
        // mapBasedMM = new MapBasedMovement(s);
        this.gdrrt = new GDRRTPlanner(this.obstacleFilePath);
    }

    public GDRRTMovement(GDRRTMovement proto) {
        super(proto);
        this.startLoc = proto.startLoc.clone();
        this.endLoc = proto.endLoc.clone();
        this.obstacleFilePath = proto.obstacleFilePath;
        // this.drone_route=proto.drone_route;
        // mapBasedMM = proto.mapBasedMM.replicate();
        this.gdrrt = new GDRRTPlanner(this.obstacleFilePath);
    }

    public GDRRTMovement replicate() {
        return new GDRRTMovement(this);
    }

    @Override
    public Path getPath() {
        if (reachedEnd)
            return null;

        if (gdrrt == null) {
            gdrrt = new GDRRTPlanner(this.obstacleFilePath);
        }

        if (!gdrrt.isInitialized()) {
            gdrrt.init(getHost().getLocation(), endLoc);
        }

        Path p = gdrrt.getNextPath();
        nextPath = p;

        
        if (p == null) {
            reachedEnd = true;
            return null;
        }

        if (!gdrrt.isInitialized()) {
            reachedEnd = true;
        }
        return p;
    }

    @Override
    public Coord getInitialLocation() {
        Coord initLoc = this.startLoc.clone();
        return initLoc;
    }

    @Override
    public double nextPathAvailable() {
        if(reachedEnd) {
            return Double.MAX_VALUE; // no new paths available until getPath() is called again
        }
        return 0;
    }

    // public void appendPath(Path p, String droneRouteFile) {
    //     droneRouteFile = droneRouteFile.replace("obstacles.wkt", "droneRoute.wkt");
    //     try {
    //         File file = new File(droneRouteFile);

    //         if (file.exists()) {
    //             // File exists → append
    //             FileWriter writer = new FileWriter(file, true);
    //             writer.write(formatPath(p));
    //             writer.write(System.lineSeparator());
    //             writer.close();
    //         } else {
    //             // File does not exist → create and write
    //             FileWriter writer = new FileWriter(file);
    //             writer.write(formatPath(p));
    //             writer.write(System.lineSeparator());
    //             writer.close();
    //         }

    //     } catch (IOException e) {
    //         e.printStackTrace();
    //     }
    // }

    // public String formatPath(Path p) {
    //     Pattern pattern = Pattern.compile("\\(([^,]+),([^\\)]+)\\)");
    //     Matcher matcher = pattern.matcher(p.toString());

    //     List<String> points = new ArrayList<>();

    //     while (matcher.find()) {
    //         String x = matcher.group(1).trim();
    //         String y = matcher.group(2).trim();
    //         points.add(x + " " + y);
    //     }

    //     // remove last coordinate
    //     if (!points.isEmpty()) {
    //         points.remove(points.size() - 1);
    //     }

    //     return "LINESTRING (" + String.join(",", points) + ")";
    // }

}
